Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from failing the test
  return false
})

beforeEach(() => {
  cy.visit('https://atlascraft.onrender.com/')
})

describe('Password Testing', () => {
  it('password retrieval testing 1 - invalid UserName', () => {
    cy.get('form > .MuiGrid-container > :nth-child(2) > .MuiTypography-root').click()
    cy.get('#\\:r0\\:').type('IAmNoUserName')
    cy.get('#\\:r1\\:').type('test1234')
    cy.get('#\\:r2\\:').type('test1234')
    cy.get('#\\:r3\\:').type('test')
    cy.get('#\\:r4\\:').type('test')
    cy.get('.MuiButton-containedPrimary').click()
    cy.wait(1000)
  })
  it('password retrieval testing 2 - invalid new password', () => {
    cy.get('form > .MuiGrid-container > :nth-child(2) > .MuiTypography-root').click()
    cy.get('#\\:r0\\:').type('AtlasTester3')
    cy.get('#\\:r1\\:').type('test12345')
    cy.get('#\\:r2\\:').type('test1234')
    cy.get('#\\:r3\\:').type('test')
    cy.get('#\\:r4\\:').type('test')
    cy.get('.MuiButton-containedPrimary').click()
    cy.get('#\\:r5\\:').type('AtlasTester3')
    cy.get('#\\:r6\\:').type('test1234')
    cy.get('form > .MuiButtonBase-root').click()
    cy.wait(1000)
  })
  it('password retrieval testing 3 - invalid security answers', () => {
    cy.get('form > .MuiGrid-container > :nth-child(2) > .MuiTypography-root').click()
    cy.get('#\\:r0\\:').type('AtlasTester3')
    cy.get('#\\:r1\\:').type('test12345')
    cy.get('#\\:r2\\:').type('test1234')
    cy.get('#\\:r3\\:').type('test12345')
    cy.get('#\\:r4\\:').type('test123456')
    cy.get('.MuiButton-containedPrimary').click()
    cy.wait(1000)
  })
  it('password retrieval testing 4 - retrieve password', () => {
    cy.get('form > .MuiGrid-container > :nth-child(2) > .MuiTypography-root').click()
    cy.get('#\\:r0\\:').type('AtlasTester3')
    cy.get('#\\:r1\\:').type('test1234')
    cy.get('#\\:r2\\:').type('test1234')
    cy.get('#\\:r3\\:').type('test')
    cy.get('#\\:r4\\:').type('test')
    cy.get('.MuiButton-containedPrimary').click()
    cy.get('#\\:r5\\:').type('AtlasTester3')
    cy.get('#\\:r6\\:').type('test1234')
    cy.get('form > .MuiButtonBase-root').click()
    cy.wait(1000)
  })
  it('password change testing 1 - change password', () => {
    cy.get('#\\:r0\\:').type('AtlasTester3')
    cy.get('#\\:r1\\:').type('test1234')
    cy.get('form > .MuiButtonBase-root').click()
    cy.get('.MuiAvatar-root').click()
    cy.get('.MuiList-root > div > :nth-child(2)').click()
    cy.get('#\\:ro\\:').type('test1234')
    cy.get('#\\:rp\\:').type('test1234')
    cy.get('#\\:rq\\:').type('test1234')
    cy.get('.MuiButton-containedPrimary').click()
    cy.get('#\\:r1h\\:').type('AtlasTester3')
    cy.get('#\\:r1i\\:').type('test1234')
    cy.get('form > .MuiButtonBase-root').click()
    cy.wait(1000)
  })
  it('password change testing 2 - invalid new password', () => {
    cy.get('#\\:r0\\:').type('AtlasTester3')
    cy.get('#\\:r1\\:').type('test1234')
    cy.get('form > .MuiButtonBase-root').click()
    cy.get('.MuiAvatar-root').click()
    cy.get('.MuiList-root > div > :nth-child(2)').click()
    cy.get('#\\:ro\\:').type('test1234')
    cy.get('#\\:rp\\:').type('test1234')
    cy.get('#\\:rq\\:').type('test123456')
    cy.get('.MuiButton-containedPrimary').click()
  })
})